# Generated by Django 4.2.8 on 2023-12-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorymaster',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=45)),
                ('category_name', models.CharField(max_length=20)),
                ('category_status', models.CharField(max_length=10)),
                ('admin_id', models.IntegerField()),
                ('d', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customermaster',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.CharField(blank=True, max_length=75, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('Door_no', models.CharField(blank=True, max_length=10, null=True)),
                ('cus_type', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_id', models.IntegerField()),
                ('d', models.IntegerField()),
                ('status', models.CharField(default='Active', max_length=10)),
                ('store_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productmaster',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField()),
                ('store_id', models.IntegerField(default=6)),
                ('product_name', models.CharField(max_length=30)),
                ('product_code', models.CharField(max_length=45)),
                ('product_cat_id', models.IntegerField()),
                ('product_subcat_id', models.IntegerField(blank=True, null=True)),
                ('product_unit', models.IntegerField()),
                ('net_quantity', models.CharField(max_length=15)),
                ('product_status', models.CharField(max_length=10)),
                ('mrp', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('tax_system', models.IntegerField(default=0)),
                ('o_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('sales_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('sale_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('product_discount', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('d', models.IntegerField(default=0)),
                ('image_1', models.FileField(blank=True, null=True, upload_to='featured/')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='featured/')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='featured/')),
                ('image_4', models.FileField(blank=True, null=True, upload_to='featured/')),
                ('image_5', models.FileField(blank=True, null=True, upload_to='featured/')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategorymaster',
            fields=[
                ('subcat_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_code', models.CharField(max_length=45)),
                ('subcategory_name', models.CharField(max_length=30)),
                ('subcat_status', models.CharField(max_length=10)),
                ('admin_id', models.IntegerField()),
                ('d', models.IntegerField(default=0)),
                ('category_id_subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categorymaster')),
            ],
        ),
        migrations.CreateModel(
            name='Inventorymaster',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status_inv', models.CharField(default='Active', max_length=10)),
                ('admin_id', models.CharField(max_length=45)),
                ('store_id', models.IntegerField()),
                ('a_stock', models.CharField(default='0', max_length=50)),
                ('c_stock', models.CharField(default='0', max_length=45)),
                ('s_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.CharField(default='0', max_length=10)),
                ('d', models.IntegerField(default=0)),
                ('product_id_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmaster')),
            ],
        ),
    ]
