# Generated by Django 4.2.8 on 2023-12-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='featured/'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='featured/'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='featured/'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='featured/'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='featured/'),
        ),
    ]
