# Generated by Django 4.2.8 on 2024-01-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productmaster_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymaster',
            name='cat_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
