# Generated by Django 4.2.8 on 2024-01-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_categorymaster_cat_image_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='latest_product',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='review_product',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='top_rate_product',
            field=models.IntegerField(default=0),
        ),
    ]
