# Generated by Django 4.2.8 on 2024-01-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productmaster_latest_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedList',
            fields=[
                ('featured_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmaster')),
            ],
        ),
    ]
