# Generated by Django 4.2.8 on 2024-01-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_featuredlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredlist',
            name='description',
            field=models.TextField(max_length=90),
        ),
    ]
