# Generated by Django 4.2.8 on 2024-01-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_featuredlist_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturedList',
            new_name='Newfeatureditems',
        ),
    ]
