# Generated by Django 4.2.8 on 2024-01-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_featuredlist_newfeatureditems'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedList',
            fields=[
                ('featured_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=90)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmaster')),
            ],
        ),
        migrations.DeleteModel(
            name='Newfeatureditems',
        ),
    ]
