# Generated by Django 4.2.8 on 2024-01-04 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_newfeatured_delete_featuredlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myfeatureditems',
            fields=[
                ('featured_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField()),
                ('store_id', models.IntegerField(default=6)),
                ('description', models.TextField(max_length=90)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmaster')),
            ],
        ),
    ]
