# Generated by Django 4.2.8 on 2024-01-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
