# Generated by Django 4.2.8 on 2024-01-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_aboutus_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('town_city', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('apartment', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ship_to_different_address', models.BooleanField(default=False)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('paypal', 'Paypal'), ('gpay', 'Google Pay'), ('phonepe', 'PhonePe'), ('cash', 'Cash On Delivery')], max_length=255)),
            ],
            options={
                'db_table': 'store_billing',
            },
        ),
    ]
