# Generated by Django 5.0.1 on 2024-01-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
