# Generated by Django 5.0.1 on 2024-02-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='YOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ytitle', models.CharField(max_length=255)),
                ('Yimage', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('Yprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('click_count', models.IntegerField(default=0)),
                ('cancel_status', models.CharField(choices=[('Cancel Order', 'Cancel Order'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Canceled Successfully', 'Canceled Successfully'), ('On Hold', 'On Hold')], default='Pending', max_length=50)),
            ],
        ),
    ]
