# Generated by Django 5.0.1 on 2024-02-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=300)),
                ('date', models.DateField(default='2024-01-01')),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('retitle', models.CharField(default='', max_length=255)),
                ('recontent', models.CharField(default='', max_length=300)),
                ('redate', models.DateField(default='2024-01-01')),
                ('relink', models.URLField(blank=True, default='', null=True)),
                ('reimage', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('cate', models.CharField(default='', max_length=255)),
                ('para', models.CharField(default='', max_length=555)),
            ],
        ),
    ]
