# Generated by Django 5.0.1 on 2024-02-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_blg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blg',
            name='para',
            field=models.CharField(blank=True, default='', max_length=555, null=True),
        ),
    ]
