# Generated by Django 5.0.1 on 2024-02-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_blg_para'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('town_city', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('apartment', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('products', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orderlistdetails',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id_id', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id_id', models.IntegerField()),
            ],
        ),
    ]
