# Generated by Django 5.0.2 on 2024-02-08 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_checkout_orderlistdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmaster'),
        ),
        migrations.AlterField(
            model_name='orderlistdetails',
            name='product_id_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmaster'),
        ),
    ]
