# Generated by Django 5.0.2 on 2024-02-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_checkout1_delete_checkout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checkout1',
            new_name='Checkout',
        ),
    ]
