# Generated by Django 5.0.2 on 2024-02-09 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_rename_checkout1_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlistdetails',
            old_name='product_id_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='orderlistdetails',
            old_name='user_id_id',
            new_name='user_id',
        ),
    ]
