# Generated by Django 5.0.2 on 2024-02-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_rename_product_id_id_orderlistdetails_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorder',
            name='cancel_status',
            field=models.CharField(choices=[('Cancel Order', 'Cancel Order'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Canceled Successfully', 'Canceled Successfully'), ('On Hold', 'On Hold')], default='Cancel Order', max_length=50),
        ),
    ]
