# Generated by Django 5.0.2 on 2024-02-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_yorder_cancel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('Return_Reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='cancel_status',
            field=models.CharField(choices=[('Cancel Order', 'Cancel Order'), ('Order Cancelled', 'Order Canceled'), ('Your Order Already Shipped Contact Your Delivery Partner', 'Your Order Already Shipped Contact Your Delivery Partner')], default='Cancel Order', max_length=500),
        ),
        migrations.AddField(
            model_name='checkout',
            name='return_status',
            field=models.CharField(choices=[('Return Order', 'Return Order'), ('Return successfull', 'Return successfull'), ('Cannot Able to Return Order', 'Cannot Able to Return Order')], default='Return Order', max_length=500),
        ),
    ]
